### ISSUE TITLE
FateID

### ISSUE THREAD

**Issue by rcannood** [dynverse/dynmethods#81]
Hello @dgrun

This issue is for discussing the wrapper for your trajectory inference method, FateID, which we wrapped for our benchmarking study ([10.1101/276907](https://doi.org/10.1101/276907)). In our [dynmethods](https://github.com/dynverse/dynmethods) framework, we collected some meta information about your method, and created a docker wrapper so that all methods can be easily run and compared. The code for this wrapper is located in [a docker container](https://github.com/dynverse/dynmethods/tree/master/containers/fateid). The way this container is structured is described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html).

We are creating this issue to ensure your method is being evaluated in the way it was designed for. The checklist below contains some important questions for you to have a look at.

- [ ] **Parameters**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/fateid/definition.yml) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#parameters))
  - Are all important parameters described in this file?
  - For each parameter, is the proposed default value reasonable?
  - For each parameter, is the proposed parameter space reasonable (e.g. lower and upper boundaries)?
  - Is the description of the parameters correct and up-to-date?
- [ ] **Input**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/fateid/definition.yml) and loaded in [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/fateid/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#input))
  - Is the correct type of expression requested (raw counts or normalised expression)?
  - Is all prior information (required or optional) requested?
  - Would some other type of prior information help the method?
- [ ] **Output**, defined in [definition.yml](https://github.com/dynverse/dynmethods/tree/master/containers/fateid/definition.yml) and saved in [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/fateid/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#output))
  - Is the output correctly processed towards the [common trajectory model](https://github.com/dynverse/dynwrap#dynwrap)? Would some other postprocessing method make more sense?
  - Is all relevant output saved (dimensionality reduction, clustering/grouping, pseudotime, ...)
- [ ] **Wrapper script**, see [run.R](https://github.com/dynverse/dynmethods/tree/master/containers/fateid/run.R) ([more info](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html#doing-trajectory-inference))
  - This is a script that is executed upon starting the docker container. It will receive several input files as defined by `definition.yml`, and is expected to produce certain output files, also as defined by `definition.yml`.
  - Is the script a correct representation of the general workflow a user is expected to follow when they want to apply your method to their data?
- [ ] **Quality control**, see [the qc worksheet](https://docs.google.com/spreadsheets/d/1GWWdndfTPtXPsCXK07jU03MmhIJHmv28E7YiMnQ_0Xo//edit#gid=271451895)
  - We also evaluated the implementation of a method based on a large check list of good software software development practices.
  - Are the answers we wrote down for your method correct and up to date? Do you disagree with certain answers? (Feel free to leave a comment in the worksheet)
    - You can improve the QC score of your method by implementing the required changes and letting us know. *Do not gloss over this, as it is the easiest way to improve the overall ranking of your TI method in our study!*

The most convenient way for you to test and adapt the wrapper is to install [dyno](https://github.com/dynverse/dyno), download and modify [these files](https://github.com/dynverse/dynmethods/tree/master/containers/fateid), and run your method on a dataset of interest or one of our synthetic toy datasets. This is further described in [this vignette](https://dynverse.github.io/dynwrap/articles/create_ti_method_docker.html). Once finished, we prefer that you [fork the dynmethods repository](https://github.com/dynverse/dynmethods), make the necessary changes, and send us a pull request. Alternatively, you can also send us the files and we will make the necessary changes.

If you have any further questions or remarks, feel free to reply to this issue.

Kind regards,
@rcannood and @zouter

**Comment by dgrun** [comment]
Dear Robrecht,

I don't think it is a good idea to include FateID into the trajectory
benchmarking, since it is not designed for the inference of complex
trajectories. The goal of this method is a probabilistic quantification of
fate bias. Although the package offers limited support for trajectory
inference by principal curve fitting in a dimensional reduction
representation it is not designed for resolving complex technologies. I
will work on methods in the future for exploiting fate bias in a more
sophisticated way for the purpose of trajectory inference.

A current shortcoming is, that trajectories are derived by this rather
simple procedure in a dimensional reduction representation. In the future I
will try to include the FateID probabilities as prior information into the
StemID analysis. This would then be more appropriate for benchmarking...

I saw you also included STEMNET which has a very similar objective to
FateID. Do you test the two method in the same way as all other methods, or
are they subject to separate benchmaking?

Thanks!


Best wishes,
Dominic


On Fri, Jun 29, 2018 at 3:11 PM, Robrecht Cannoodt <notifications@github.com

**Comment by rcannood** [comment]
Hello Dominic,

There are actually quite a few methods like this that are already implemented in dynbenchmark, namely FateID, GPfates, GrandPrix, MFA, SCOUP, and STEMNET. It would indeed be interesting to perform a more in-depth analysis between only these six methods. For now, they are being evaluated just like all the other trajectory inference methods.

Kind regards,
Robrecht

**Comment by dgrun** [comment]
Dear Robrecht,

I'm not sure it is a fair comparison to benchmark these methods in the same
way like the other methods more suitable for inferring complex lineage
trees. The objective of these methods is quite different, at least for
STEMNET and FateID...

Anyway, I would like to let you know that I updated FateID on CRAN (version
0.1.3). I implemented an adaptive learning scheme in the fateBias function
(parameter adapt=TRUE). If you test the method it would be useful to test
in this mode.

Thanks a lot!

Best wishes,
Dominic

On Tue, Jul 31, 2018 at 5:22 PM, Robrecht Cannoodt <notifications@github.com

**Comment by rcannood** [comment]
Hey Dominic, 

Sorry, I forgot to follow up on this issue. STEMNET, FateID and others were not removed from our benchmark because we believe they are also a relevant category of methods to compare against. 

The [large overview figure](https://github.com/dynverse/dynbenchmark_results/blob/master/08-summary/results_suppfig.pdf) shows that these methods work well, except in terms of scalability.

I'm closing this issue for now. If you have made changes to RaceID / StemID or FateID for which you believe that they might improve performance in one of the criterion, feel free to contact us again.

Kind regards
Robrecht

**Comment by dgrun** [comment]
Dear Robrecht,

thanks for letting me know. FateID seems to work well indeed.

I do have a question regarding RaceID/StemID. Did you run it with
nmode=TRUE in the end?

In case you haven't done yet I would like to ask you to rerun with the
RaceID parameter metric="logpearson".
With this setting RaceID first performs a log-transformation before the
cell-cell transcriptome correlation is computed. If cell type differences
are more influenced by many lowly expressed genes instead of few highly
expressed genes, this metric gives much better results. Could you let me
know if this improves the predictions?

Many thanks in advance!

Best wishes,
Dominic
