### ISSUE TITLE
Waddington-OT

### ISSUE THREAD

**Issue by zouter** [dynverse/dynmethods#89]
https://pypi.org/project/wot/

**Comment by zouter** [comment]
Given that the time prior information is now included in dynwrap, this should be easy to wrap

**Comment by joshua-gould** [comment]
You want to convert the transport maps to long format, correct?

On Tue, Jul 31, 2018 at 5:22 AM, Robrecht Cannoodt <notifications@github.com

**Comment by rcannood** [comment]
Hello Joshua!

No, not exactly. We want to convert the transport maps to our 'common trajectory format' (See [Figure 1 in our bioRxiv](https://www.biorxiv.org/content/biorxiv/early/2018/03/05/276907.full.pdf)). Converting the transport maps to a long format would result in a graph that is way too dense. In order to make it less sparse, I could calculate an MST, but I'm not sure this is the spirit of wot.

Robrecht

**Comment by robindar** [comment]
Hello Robrecht,

From what I understand, all methods compared in this paper are trying to build a graph (with different constraints) that best describes the evolution of the cells, and then project all cells to its edges, to get the progression values of your example.
Wot does not impose such topology constraints, it only estimates the probabillity that each cell is the ancestor/descendant of a given cell. While I am sure that the transport maps carry enough information for the construction of a milestone network, I doubt that there is a unique construction that makes sense here, so I wouldn't know what to include in this benchmark.

David

**Comment by rcannood** [comment]
Thanks for this information, David :)

Based on your explanation, we will exclude Waddington-OT from the benchmark for now.

Kind regards,
Robrecht
